repos:
  - repo: https://github.com/python/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--safe, --quiet, -l120]
        language_version: python3
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==24.4.2]
        language_version: python3
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args: ["--django"]
      - id: trailing-whitespace
        language_version: python3
        exclude: "setup.cfg|^src/bootlace/assets/"
      - id: end-of-file-fixer
        language_version: python3
        exclude: "^src/bootlace/assets/"
      - id: fix-encoding-pragma
        language_version: python3
        args: [--remove]
      - id: check-yaml
        language_version: python3
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
          - flake8-typing-imports
        exclude: "src/bootlace/_version.py"
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args: [--py311-plus, "--application-directories=.:src"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
        exclude: "src/bootlace/_version.py"
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
  - repo: https://github.com/peterdemin/pip-compile-multi
    rev: v2.6.3
    hooks:
      - id: pip-compile-multi-verify
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: "v9.0.0-beta.1"
  #   hooks:
  #     - id: eslint
  #       files: ^src/frontend/.*\.(js|jsx|ts|tsx)$
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
  #   hooks:
  #     - id: prettier
  #       files: ^src/frontend/.*\.(js|jsx|ts|tsx)$
  #       types_or:
  #         - "ts"
  #         - "javascript"
  #         - "scss"
  #         - "css"
